name: Generate Contribution Snake
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: src

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          output: |
            src/assets/github-contribution-snake.svg
            src/assets/github-contribution-snake-dark.svg
          gif_out_path: src/assets/github-contribution-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Animation Files
        run: |
          cd src
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/
          git commit -m "🔄 Update contribution snake animation [skip ci]"
          git push